# Generated by Django 3.2.23 on 2023-11-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_file',
        ),
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=models.FileField(blank=True, upload_to='image/'),
        ),
    ]
