# Generated by Django 3.2.23 on 2023-12-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20231127_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_file',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
