# Generated by Django 3.2.23 on 2023-11-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='media_file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_file',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
    ]
