# Generated by Django 3.2.23 on 2023-11-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231114_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='video_file',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
