# Generated by Django 3.2.23 on 2023-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20231115_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='profile_audios/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, default='../kang1_ojzpwj', null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='profile_videos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
