# Generated by Django 3.2.23 on 2023-12-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20231127_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, default='../kang1_ojzpwj', null=True, upload_to='media/'),
        ),
    ]
