# Generated by Django 3.2.23 on 2023-12-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20231214_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='../kang1_ojzpwj', null=True, upload_to='media/'),
        ),
    ]
